// <auto-generated />
using System;
using FinancialInsights.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialInsights.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219092531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AkahuAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AkahuAccountId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.AccountProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NzBankKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountProfiles");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryType", "Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AkahuTransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBankTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Reference")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AkahuTransactionId")
                        .IsUnique();

                    b.HasIndex("TransactionDateUtc");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.TransactionAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("SpendTypeCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransactionTypeCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpendTypeCategoryId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("TransactionTypeCategoryId");

                    b.ToTable("TransactionAnnotations");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.AccountProfile", b =>
                {
                    b.HasOne("FinancialInsights.Api.Domain.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("FinancialInsights.Api.Domain.Entities.AccountProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinancialInsights.Api.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.TransactionAnnotation", b =>
                {
                    b.HasOne("FinancialInsights.Api.Domain.Entities.Category", "SpendTypeCategory")
                        .WithMany("SpendTypeAnnotations")
                        .HasForeignKey("SpendTypeCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinancialInsights.Api.Domain.Entities.Transaction", "Transaction")
                        .WithOne("Annotation")
                        .HasForeignKey("FinancialInsights.Api.Domain.Entities.TransactionAnnotation", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialInsights.Api.Domain.Entities.Category", "TransactionTypeCategory")
                        .WithMany("TransactionTypeAnnotations")
                        .HasForeignKey("TransactionTypeCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SpendTypeCategory");

                    b.Navigation("Transaction");

                    b.Navigation("TransactionTypeCategory");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.Account", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("SpendTypeAnnotations");

                    b.Navigation("TransactionTypeAnnotations");
                });

            modelBuilder.Entity("FinancialInsights.Api.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Annotation");
                });
#pragma warning restore 612, 618
        }
    }
}
